import express, { Router } from "express";
import authRouter from "../../auth/auth.route";
import userRouter from "../../user/user.route";
import settingsRouter from "../../settings/settings.route";
import clinicRouter from "../../clinic/clinic.route";
import plansRouter from "../../plans/plans.route";
import clinicMemberRouter from "../../clinicMember/clinicMember.route";
import sessionRouter from "../../session/session.route";
import integrationRouter from "../../integration/integration.route";
import clientRouter from "../../client/client.route";
import appointmentRouter from "../../appointment/appointment.route";
import stripeRouter from "../../stripe/stripe.route";
import providerRouter from "../../provider/provider.route";
import assessmentRouter from "../../assessment/assessment.route";
import invoiceRouter from "../../invoice/invoice.route";
import subscriptionRouter from "../../subscription/subscription.routes";
import reportRouter from "../../report/report.routes";
import analyticsRouter from "../../analytics/analytics.routes";
import dashboardRouter from "../../dashboard/dashboard.route";
import issueRouter from "../../issue/issue.route";
import transactionRouter from "../../transaction/transaction.route";
import clinicalNoteRouter from "../../clinicalNote/clinicalNote.route";
import aiAssistantRouter from "../../ai-assistant/ai-assistant.route";
import notificationRouter from "../../notification/notification.route";

const mainRouter: Router = express.Router();

mainRouter.use("/auth", authRouter);
mainRouter.use("/user", userRouter);
mainRouter.use("/setting", settingsRouter);
mainRouter.use("/clinic", clinicRouter);
mainRouter.use("/plans", plansRouter);
mainRouter.use("/clinic-member", clinicMemberRouter);
mainRouter.use("/session", sessionRouter);
mainRouter.use("/integration", integrationRouter);
mainRouter.use("/client", clientRouter);
mainRouter.use("/appointment", appointmentRouter);
mainRouter.use("/stripe", stripeRouter);
mainRouter.use("/provider", providerRouter);
mainRouter.use("/assessment", assessmentRouter);
mainRouter.use("/invoice", invoiceRouter);
mainRouter.use("/subscription", subscriptionRouter);
mainRouter.use("/report", reportRouter);
mainRouter.use("/analytics", analyticsRouter);
mainRouter.use("/dashboard", dashboardRouter);
mainRouter.use("/issue", issueRouter);
mainRouter.use("/transaction", transactionRouter);
mainRouter.use("/clinical-note", clinicalNoteRouter);
mainRouter.use("/ai-assistant", aiAssistantRouter);
mainRouter.use("/notification", notificationRouter);

export default mainRouter;
