const getUserSelect = {
  id: true,
  firstName: true,
  lastName: true,
  email: true,
  role: true,
  avatar: true,
  isEmailVerified: true,
  fcmToken: true,
  phoneNumber: true,
  countryCode: true,
  isRestricted: true,
  restrictionReason: true,
  bio: true,
  isOnline: true,
  lastSeen: true,
  lastLoginAt: true,
  lastPasswordChangedAt: true,
  createdAt: true,
  updatedAt: true,
  clinicMemberships: {
    select: {
      id: true,
      role: true,
      clinicianToken: true,
      availability: true,
      specialization: true,
      createdAt: true,
      updatedAt: true,
      clinic: {
        select: {
          id: true,
          name: true,
          email: true,
          phoneNumber: true,
          countryCode: true,
          address: true,
          logo: true,
          color: true,
          description: true,
          publicToken: true,
          isActive: true,
          activatedAt: true,
        },
      },
    },
  },
  ownedClinics: {
    select: {
      id: true,
      name: true,
      email: true,
      phoneNumber: true,
      countryCode: true,
      address: true,
      logo: true,
      color: true,
      description: true,
      publicToken: true,
      isActive: true,
      activatedAt: true,
    },
  },
};

export default { getUserSelect };
